export function mockTrelloExportJson(len) {
  return {
    id: 'idBoard',
    name: 'hello-board',
    desc: '',
    descData: null,
    closed: false,
    dateClosed: null,
    idOrganization: 'idOrg',
    shortLink: '',
    dateLastActivity: '2021-12-10T09:00:43.252Z',
    dateLastView: '2021-12-10T09:00:43.252Z',
    idTags: [],
    creationMethod: 'automatic',
    idMemberCreator: 'idUser',
    pinned: false,
    starred: false,
    url: 'https://trello.com/b/qoBz7TLE/hello-trello',
    subscribed: false,
    labelNames: {
      green: '完成',
      red: '警告',
      blue: '',
    },
    cards: [
      {
        id: 'idCard',
        name: 'doing1',
        desc: '',
        descData: {
          emoji: {},
        },
        idList: 'idList',
        idBoard: 'idBoard',
        idLabels: ['label1'],
        idChecklists: ['61b3169db3dfa4373e95a27b'],
        idMembers: [],
        labels: [],
        closed: false,
        dateLastActivity: '2021-12-10T09:00:43.252Z',
        idMemersVoted: [],
        idShort: 2,
        isTemplate: false,
        cardRole: null,
        dueReminder: null,
        dueComplete: false,
        due: null,
        cover: {},
        attachments: [],
        customFieldItems: [],
      },
    ],
    lists: [
      {
        id: 'idList',
        name: 'to-do',
        closed: false,
        idBoard: '61a4fa788bd06112ae1024cb',
      },
    ],
    labels: [
      {
        id: 'idLabel',
        idBoard: 'idBoard',
        name: '测试标签',
        color: 'purple',
      },
    ],
    checklists: [
      {
        id: '61b3169db3dfa4373e95a27b',
        name: 'test checklist',
        idCard: '61b315dea50f318496c59840',
        checkItems: [
          {
            idChecklist: '61b3169db3dfa4373e95a27b',
            state: 'complete',
            id: '61b316a7dce17a5b97006b16',
            name: 'ckeditor',
            nameData: {
              emoji: {},
            },
            pos: 16879,
            due: null,
            idMember: null,
          },
          {
            idChecklist: '61b3169db3dfa4373e95a27b',
            state: 'incomplete',
            id: '61b316ab877ce337dbc11e2e',
            name: 'prosemirror',
            nameData: {
              emoji: {},
            },
            pos: 33786,
            due: null,
            idMember: null,
          },
        ],
      },
    ],
    customFields: [{}],
    members: [
      {
        id: 'idUser',
        username: 'uptonking1',
        fullName: 'uptonking',
        avatarUrl: '',
        memberType: 'normal',
      },
    ],
    memberships: [
      {
        id: 'id1',
        idMember: 'idUser',
        memberType: 'admin',
        unconfirmed: false,
        deactivated: false,
      },
    ],
    limits: {},
    prefs: {
      cardCovers: true,
    },
    actions: [
      {
        id: 'idAction',
        idMemberCreator: 'idUser',
        data: {},
        type: 'updateCard',
        date: '2021-12-10T09:00:43.262Z',
      },
    ],
  };
}
